version: '3'

services:
  db:
    image: 'mysql:8.0'
    ports:
           - "3306:3306"
    environment:
           - MYSQL_ROOT_PASSWORD=database_password_goes_here
           - MYSQL_DATABASE=doodledb
           - MYSQL_ROOT_HOST=%
    volumes:
           - ./my-datavolume:/var/lib/mysql
    healthcheck:
           test: ["CMD","mysqladmin","ping","-h","localhost"]
           timeout: 20s
           retries: 10
    restart: always
  backendserver:
    image: 'backend-image'
    ports:
           - "8080:8080"
    links:
           - "db"
    depends_on:
           - "db"
    restart: always
  frontend:
    image: 'frontend-image'
    links:
           - "backendserver"
    depends_on:
           - "backendserver"
    ports:
           - "80:80"

